baseURL = "https://littleclusters.com/"
languageCode = "en-us"
title = "LittleClusters"
theme = "hugo-book"
enableGitInfo = true
enableRobotsTXT = true
copyright = '[Â© CC BY 4.0](https://github.com/littleclusters/docs/blob/main/LICENSE)'

disableKinds = ["taxonomy", "term", "rss"]

[params]
  BookTheme = "auto"
  BookFavicon = "fa-feather.svg"
  BookLogo = "fa-feather.svg"
  BookSection = "/"
  BookSearch = true
  BookComments = false

  Challenges = [
    "kv-store",
  ]

[menu]
[[menu.after]]
  name = "GitHub"
  url = "https://github.com/littleclusters/lc"
  weight = 2000

[markup]
[markup.goldmark.renderer]
  unsafe = true
[markup.tableOfContents]
  startLevel = 2
  endLevel = 4
